apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firstchart.fullname" . }}
  namespace: {{ .Values.project.namespace }}
  labels:
    app: api
    author: {{ .Values.project.author }}
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api
      author: {{ .Values.project.author }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        author: {{ .Values.project.author }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
        - env:
          - name: PORT
            value: {{ .Values.image.port }}
