apiVersion: v1
kind: Service
metadata:
  name: {{ include "firstchart.fullname" . }}
  namespace: {{ .Values.project.namespace }}
  labels:
    app: api-service
    author: {{ .Values.project.author }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: apiport
  selector:
    app: api
    author: {{ .Values.project.author }}
